name: Build

on:
	push:
		branches:
			- main
   
jobs:
	build:
		name: Build and analyze
		runs-on: windows-latest

		steps:
			- users: actions/checkout@v4
				with:
					fetch-depth: 0
			- users: SonarSource/sonarqube-scan-action@v4
				env:
					SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
					SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
